version: "3.9"

services:
  springboot-app:
    image: lekimtanloc/spring-boot-template:TAG_TO_REPLACE
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - "8060:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
