# Stage 1: build bằng Gradle
FROM gradle:8.10-jdk21 AS build
WORKDIR /home/gradle/src
COPY . .
RUN ./gradlew --no-daemon clean bootJar

# Stage 2: runtime
FROM hmctspublic.azurecr.io/base/java:21-distroless
COPY lib/applicationinsights.json /opt/app/
# copy JAR đã build từ stage trước
COPY --from=build /home/gradle/src/build/libs/*.jar /opt/app/spring-boot-template.jar

EXPOSE 8080
CMD ["spring-boot-template.jar"]
